id: P007023
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4343
  title: 'མཁས་གྲུབ་བླ་མ་དུ་མའི་གསུང་བྱིན་རླབས་ཅན་ཕྱོགས་གཅིག་ཏུ་བསྡུས་པ།

    '
  author: ''
  volumes:
    04d29d944d944791966bcf159e9f80f4:
      image_group_id: I3CN4572
      title: ''
      volume_number: 1
      total_pages: 260
ebook_metadata:
  title: 'མཁས་གྲུབ་བླ་མ་དུ་མའི་གསུང་བྱིན་རླབས་ཅན་ཕྱོགས་གཅིག་ཏུ་བསྡུས་པ།

    '
  author: ''
  sku: P007023
  cover: cover.jpg
  layers:
  - pagination
