id: ICF1FCFEC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T22:41:47+00:00'
last_modified: '2022-06-08T13:16:59.649079+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4343
  title: 'མཁས་གྲུབ་བླ་མ་དུ་མའི་གསུང་བྱིན་རླབས་ཅན་ཕྱོགས་གཅིག་ཏུ་བསྡུས་པ།

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4D93:
      image_group_id: I3CN4572
      title: Volume 1 of mkhas grub bla ma du ma'i gsung byin rlabs can phyogs gcig
        tu bsdus pa/
      total_pages: 260
      order: 1
      base_file: 4D93.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
